language: python
sudo: false
cache:
  - pip
python:
  - nightly
  - 3.6
  - 3.5
  - 3.4
env:
  global:
    - ASYNC_TEST_TIMEOUT=15
services:
  - mysql
  - postgresql
  - docker

# installing dependencies
before_install:
  - nvm install 6; nvm use 6
  - npm install
  - npm install -g configurable-http-proxy
  - |
    if [[ $JUPYTERHUB_TEST_DB_URL == mysql* ]]; then
      service stop mysql || echo 'mysql not running'
      docker run -d -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -p 3306:3306 mysql:5.7
      echo -n 'waiting for mysql'
      for i in {1..60}; do
        if mysql --user root -e '\q' 2>/dev/null; then
          echo 'done'
          break
        else
          echo -n '.'
          sleep 1
        fi
      done
      mysql -e 'CREATE DATABASE jupyterhub CHARACTER SET utf8 COLLATE utf8_general_ci;'
      mysql -e 'CREATE DATABASE jupyterhub_upgrade CHARACTER SET utf8 COLLATE utf8_general_ci;'
      pip install 'mysql-connector<2.2'
    elif [[ $JUPYTERHUB_TEST_DB_URL == postgresql* ]]; then
      psql -c 'create database jupyterhub;' -U postgres
      psql -c 'create database jupyterhub_upgrade;' -U postgres
      pip install psycopg2
    fi
install:
  - pip install -U pip
  - pip install --pre -r dev-requirements.txt .
  - pip freeze

# running tests
script:
  - |
    if [[ ! -z "$JUPYTERHUB_TEST_DB_URL" ]]; then
      # if testing upgrade-db, run `jupyterhub token` with 0.7
      # to initialize an old db. Used in upgrade-tests
      export JUPYTERHUB_TEST_UPGRADE_DB_URL=${JUPYTERHUB_TEST_DB_URL}_upgrade
      # use virtualenv instead of venv because venv doesn't work here
      python -m pip install virtualenv
      python -m virtualenv old-hub-env
      ./old-hub-env/bin/python -m pip install jupyterhub==0.7.2 psycopg2 'mysql-connector<2.2'
      ./old-hub-env/bin/jupyterhub token kaylee \
        --JupyterHub.db_url=$JUPYTERHUB_TEST_UPGRADE_DB_URL \
        --Authenticator.whitelist="{'kaylee'}" \
        --JupyterHub.authenticator_class=jupyterhub.auth.Authenticator
    fi
  - pytest -v --maxfail=2 --cov=jupyterhub jupyterhub/tests
after_success:
  - codecov

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://localhost.jovyan.org:8000
    - python: 3.6
      env: JUPYTERHUB_TEST_DB_URL=mysql+mysqlconnector://root@127.0.0.1/jupyterhub
    - python: 3.6
      env: JUPYTERHUB_TEST_DB_URL=postgresql://postgres@127.0.0.1/jupyterhub
    - python: 3.6
      env: TEST=db-upgrade
  allow_failures:
    - python: nightly
