# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
sudo: false
python:
    - 3.4
    - 3.3
before_install:
    - npm install
    - npm install -g configurable-http-proxy
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse -r dev-requirements.txt .
    - pip install -f travis-wheels/wheelhouse ipython[notebook]
script:
    - py.test --cov jupyterhub jupyterhub/tests -v
after_success:
    - coveralls
