dist: bionic
language: python
cache:
  - pip
python:
  # These lines will yield additional jobs, and they will be separated out as
  # allowed to fail in the Travis web user interface as compared to if we would
  # add them in the matrix.include below instead.
  - &allowed_failure_1 3.8
  - &allowed_failure_2 nightly
env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_TCP_PORT=13306
services:
  - postgresql
  - docker

# installing dependencies
before_install:
  - set -e
  - nvm install 6; nvm use 6
  - npm install
  - npm install -g configurable-http-proxy
  - |
    # setup database
    if [[ $JUPYTERHUB_TEST_DB_URL == mysql* ]]; then
      unset MYSQL_UNIX_PORT
      DB=mysql bash ci/docker-db.sh
      DB=mysql bash ci/init-db.sh
      # FIXME: mysql-connector-python 8.0.16 incorrectly decodes bytes to str
      # ref: https://bugs.mysql.com/bug.php?id=94944
      pip install 'mysql-connector-python==8.0.11'
    elif [[ $JUPYTERHUB_TEST_DB_URL == postgresql* ]]; then
      psql -c "CREATE USER $PGUSER WITH PASSWORD '$PGPASSWORD';" -U postgres
      DB=postgres bash ci/init-db.sh
      pip install psycopg2-binary
    fi
install:
  - pip install --upgrade pip
  - pip install --upgrade --pre -r dev-requirements.txt .
  - pip freeze

# running tests
script:
  - |
    # run tests
    if [[ -z "$TEST" ]]; then
      pytest -v --maxfail=2 --cov=jupyterhub jupyterhub/tests
    fi
  - |
    # run autoformat
    if [[ "$TEST" == "lint" ]]; then
      pre-commit run --all-files
    fi
after_success:
  - codecov
after_failure:
  - |
    # point to auto-lint-fix
    if [[ "$TEST" == "lint" ]]; then
      echo "You can install pre-commit hooks to automatically run formatting"
      echo "on each commit with:"
      echo "    pre-commit install"
      echo "or you can run by hand on staged files with"
      echo "    pre-commit run"
      echo "or after-the-fact on already committed files with"
      echo "    pre-commit run --all-files"
    fi
matrix:
  include:
    # With TEST=lint and TEST=docs we won't run pytest
    - python: 3.7
      env: TEST=lint
    # When we run pytest, we want to run it with python>=3.5 as well as with
    # various configurations. We increment the python version at the same time
    # as we test new configurations in order to reduce the number of test jobs.
    - python: 3.5
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://localhost.jovyan.org:8000
    - python: 3.6
      dist: xenial
      env:
        - JUPYTERHUB_TEST_DB_URL=mysql+mysqlconnector://root@127.0.0.1:$MYSQL_TCP_PORT/jupyterhub
    - python: 3.7
      env:
        - PGUSER=jupyterhub
        - PGPASSWORD=hub[test/:?
        # password in url is url-encoded (urllib.parse.quote($PGPASSWORD, safe=''))
        - JUPYTERHUB_TEST_DB_URL=postgresql://jupyterhub:hub%5Btest%2F%3A%3F@127.0.0.1/jupyterhub
  allow_failures:
    - python: *allowed_failure_1
    - python: *allowed_failure_2
  fast_finish: true
