# Updating CircleCI configuration from v1 to v2
version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ls

  test:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker build -t jupyterhub/jupyterhub .
      - run: docker build -t jupyterhub/jupyterhub-onbuild:${CIRCLE_TAG:-latest} onbuild

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS -e unused@example.com
      - run: docker push jupyterhub/jupyterhub-onbuild

  release:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS -e unused@example.com
      - run: docker push jupyterhub/jupyterhub-onbuild:$CIRCLE_TAG


  workflows:
    version: 2
    build-test-deploy:
      jobs:
        - build
        - test
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: master
        - release:
            requires:
              - test
            filters:
              tags:
              only: /.*/
