# Python CircleCI 2.0 configuration file
# Updating CircleCI configuration from v1 to v2
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build images
          command: |
            docker build -t jupyterhub/jupyterhub .
            docker build -t jupyterhub/jupyterhub-onbuild onbuild
            docker build -t jupyterhub/jupyterhub:alpine -f dockerfiles/Dockerfile.alpine .
            docker build -t jupyterhub/singleuser singleuser
      - run:
          name: smoke test jupyterhub
          command: |
            docker run --rm -it jupyterhub/jupyterhub jupyterhub --help
      - run:
          name: verify static files
          command: |
            docker run --rm -it -v $PWD/dockerfiles:/io jupyterhub/jupyterhub python3 /io/test.py

  docs:
    # This is the base environment that Circle will use
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout
      # Update our path
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      # Restore cached files to speed things up
      - restore_cache:
          keys:
            - cache-pip
      # Install the packages needed to build our documentation
      - run:
          name: Install NodeJS
          command: |
            # From https://github.com/nodesource/distributions/blob/master/README.md#debinstall
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --user -r dev-requirements.txt
            python3 -m pip install --user -r docs/requirements.txt
            sudo npm install -g configurable-http-proxy
            sudo python3 -m pip install --editable .

      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip
      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd docs
            make metrics html
      # Tell Circle to store the documentation output in a folder that we can access later
      - store_artifacts:
          path: docs/build/html/
          destination: html

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - build
      - docs
