# ReadTheDocs uses the `environment.yaml` so make sure to update that as well
# if you change the dependencies of JupyterHub in the various `requirements.txt`
name: jhub_docs
channels:
  # use metachannel for faster solves / less memory on RTD
  # which has memory issues with full conda-forge
  # only need to list 'leaf' dependencies here
  - https://metachannel.conda-forge.org/conda-forge/jupyterhub,sphinx,recommonmark
dependencies:
- pip
- nodejs=12
- python=3.7
- alembic
- jinja2
- pamela
- recommonmark>=0.6
- requests
- sqlalchemy>=1
- tornado>=5.0
- traitlets>=4.1
- sphinx>=1.7
- pip:
  - -r requirements.txt
