name: jupyterhub_docs
channels:
  - conda-forge
dependencies:
- nodejs
- python=3
- jinja2
- pamela
- requests
- sqlalchemy>=1
- tornado>=4.1
- traitlets>=4.1
- sphinx
- sphinx_rtd_theme
- pip:
    - recommonmark
